# Generated by Django 4.1.6 on 2023-02-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='subcategory_slug',
        ),
    ]
